### ISSUE TITLE
07: Jekyll + Bootstrap + d3 starter 

### ISSUE THREAD

**Issue by ontouchstart** [bigdata-mindstorms/jekyll-playground#10]
https://github.com/bigdata-mindstorms/jekyll-playground/tree/gh-pages/public/ontouchstart/2016/03/09

**Comment by ontouchstart** [comment]
![screen shot 2016-03-08 at 9 35 43 pm](https://cloud.githubusercontent.com/assets/951921/13623616/d69d6002-e575-11e5-9c5c-a5a25cb1ce79.png)
![screen shot 2016-03-08 at 9 35 57 pm](https://cloud.githubusercontent.com/assets/951921/13623615/d69affc4-e575-11e5-9acd-3f7c83593b0e.png)
![screen shot 2016-03-08 at 9 36 14 pm](https://cloud.githubusercontent.com/assets/951921/13623614/d69ad2f6-e575-11e5-82d3-82772f706a8a.png)

**Comment by LivingProgram** [comment]
https://github.com/bigdata-mindstorms/jekyll-playground/tree/gh-pages/public/LivingProgram/2016/03/11/Lesson07

**Comment by ontouchstart** [comment]
@LivingProgram You have a bug in it. It didn't work. Please use JavaScript console to find out why and fix it.

**Comment by ontouchstart** [comment]
@LivingProgram 

I see you didn't have a chance to fix this bug: https://github.com/bigdata-mindstorms/jekyll-playground/commit/ed2b06842d5ac3ede69f1f1c523c358268411216#commitcomment-16658792

To help you see why bugs like that happened, I made another version of the sample exercise https://github.com/bigdata-mindstorms/jekyll-playground/issues/11

When a project is getting bigger and more complex, a lot of details need to be taken care of. 

Perl programmers have a motto:  [There's more than one way to do it](https://en.wikipedia.org/wiki/There%27s_more_than_one_way_to_do_it). It is also true in the HTML5/JavaScript/CSS/DOM/D3/Jekyll world. :wink: There is no absolute right or wrong answer. But you do need to understand __every decision has its own consequences__ and learn to deal with them.

**Comment by ontouchstart** [comment]
You should also know with Git, it is easy to fix bugs:

https://github.com/bigdata-mindstorms/jekyll-playground/commit/ceab6fbcaec8d20ad950767e219a672498084264

https://github.com/bigdata-mindstorms/jekyll-playground/commit/bb0dd9d9b382db354b369758d66f3b3c89c56fc8

It is __normal__ to have bugs, but it is not __OK__ not to fix the bugs once you know where they are.

**Comment by VeroniqueSoleil** [comment]
https://github.com/bigdata-mindstorms/jekyll-playground/blob/gh-pages/public/VeroniqueSoleil/2016/03/14/README.md

**Comment by IntelligentDataMiner** [comment]
https://github.com/bigdata-mindstorms/jekyll-playground/blob/gh-pages/public/IntelligentDataMiner/2016/04/18/lesson_7/README.md

**Comment by ontouchstart** [comment]
@IntelligentDataMiner 

You had a few mistakes and typos. Take a look at my fixes:

https://github.com/bigdata-mindstorms/jekyll-playground/commit/fb0f9323c037dd279f8890dcc09acaf12f8e875d

https://github.com/bigdata-mindstorms/jekyll-playground/commit/589f7edd44ba65a93b932120f8dc2dc880dbff5d

### One more time:
It is normal to have bugs, but it is not OK not to fix the bugs once you know where they are.
