### ISSUE TITLE
08: Jekyll + Bootstrap + d3 starter  (local version)

### ISSUE THREAD

**Issue by ontouchstart** [bigdata-mindstorms/jekyll-playground#11]
This exercise is almost the same as https://github.com/bigdata-mindstorms/jekyll-playground/issues/10. The main difference is that we copy all the library files from the shared folders to the same level as our html/js files so that the 
generated pages are more portable.

https://github.com/bigdata-mindstorms/jekyll-playground/tree/gh-pages/public/ontouchstart/2016/03/12

**Comment by amarande** [comment]
请问老师：
>如何把整个目录拷到local目录下？

**Comment by ontouchstart** [comment]
这需要你们会用自己local操作系统的文件夹拷贝和git客户端。

**Comment by ontouchstart** [comment]
建议学习[CLI](https://github.com/bigdata-mindstorms/node-playground/issues/2)

**Comment by LivingProgram** [comment]
> This exercise is almost the same as 2016/03/09. The main difference is that we copy all the library files from the shared folders to the same level as our html/js files so that the generated pages are more portable.

I see that when you copy the libraries, you don't have to put the `../../../../../` in the `href` and `src` places,  so does the `../` bring you 1 folder back?

**Comment by ontouchstart** [comment]
Yes. Now do a count and fix your bug. :smile:

**Comment by ontouchstart** [comment]
To avoid coping libraries over every time you make a local folder, we can have a shared version of the Jekyll + Bootstrap + d3 starter: https://github.com/bigdata-mindstorms/jekyll-playground/issues/12

Each solution has it own pro and con. 

- In the local copy version, the generated web pages are more portable because all dependencies you need are copied into the same folder. The generated web page folder can even work offline.

- In the shared library version, your web pages have to be online and the shared libraries have to be at the specific paths. This makes your web pages less portable.

When project gets bigger and more complex, dependencies become more and more important. The more dependencies you have, the easier to have something wrong and the harder to fix them. On the other hand, if everything goes right, you will have less work to do.

Keep the balance is the art of programming.

**Comment by amarande** [comment]
https://github.com/bigdata-mindstorms/jekyll-playground/blob/gh-pages/public/amarande/03/10/README.md

**Comment by IntelligentDataMiner** [comment]
@ontouchstart 

Can you explain what you mean by "The main difference is that we copy all the library files from the shared folders to the same level as our html/js files so that the
generated pages are more portable."

Is there a difference in code or where is the "shared folder?" 
Please Elaborate

**Comment by ontouchstart** [comment]
This folder (we call local folder)

https://github.com/bigdata-mindstorms/jekyll-playground/tree/gh-pages/public/ontouchstart/2016/03/12/d3

is under the current folder

https://github.com/bigdata-mindstorms/jekyll-playground/tree/gh-pages/public/ontouchstart/2016/03/12

which is used by files like

https://bigdata-mindstorms.github.io/jekyll-playground/public/ontouchstart/2016/03/12/index.html 

A shared folder is like this 

https://github.com/bigdata-mindstorms/jekyll-playground/tree/gh-pages/d3

that can be used by files in other folders like this

https://bigdata-mindstorms.github.io/jekyll-playground/public/ontouchstart/2016/03/09/index.html

You can take a look at the source code of these files and see the difference. Pay attention to the file path.

To learn more about file path:

https://en.m.wikipedia.org/wiki/Path_(computing)

**Comment by IntelligentDataMiner** [comment]
@ontouchstart 
So are we basically taking the files shared by several programs and creating separate versions of it for each program?

**Comment by ontouchstart** [comment]
Yes, that is one way to do it.

It has pro and cons. 

Pro is the module itself becomes independent so it is  easy to copy and paste or move around. 

Con is it takes more space and doesn't get updated with the shared libraries.

**Comment by IntelligentDataMiner** [comment]
@ontouchstart 
Can you help me?
My code looks the same and seems to have no typos, but still does not work.
Generated websites
https://bigdata-mindstorms.github.io/jekyll-playground/public/IntelligentDataMiner/2016/04/21/index.html
https://bigdata-mindstorms.github.io/jekyll-playground/public/IntelligentDataMiner/2016/04/21/container.html
https://bigdata-mindstorms.github.io/jekyll-playground/public/IntelligentDataMiner/2016/04/21/container-fluid.html
https://bigdata-mindstorms.github.io/jekyll-playground/public/IntelligentDataMiner/2016/04/21/dropdown.html
(ps, in the console log for the last 3 it says that d3 is not defined)

**Comment by ontouchstart** [comment]
https://github.com/bigdata-mindstorms/jekyll-playground/blob/gh-pages/_layouts/IntelligentDataMiner/2016/04/21/default.html#L12

The js files referenced here have relative path, which means they should be at the same level as your source html/md files.

Check out my answer to your previous questions here: https://github.com/bigdata-mindstorms/jekyll-playground/issues/11#issuecomment-212688521

**Comment by ontouchstart** [comment]
You can see my folder  here

https://github.com/bigdata-mindstorms/jekyll-playground/tree/gh-pages/public/ontouchstart/2016/03/12

there are copies of those folders, d3, ...

Your folder here : https://github.com/bigdata-mindstorms/jekyll-playground/tree/gh-pages/public/IntelligentDataMiner/2016/04/21

looks almost the same as mine but those folders are missing. That is why it can not find d3.

**Comment by ontouchstart** [comment]
@IntelligentDataMiner And please read previous questions and answers in this same issue. You might have the same question. Learn from other people.

**Comment by IntelligentDataMiner** [comment]
@ontouchstart 
Is there a way to copy github files and folders without going into each file and copying the text and pasting it into a new file? thanks

**Comment by ontouchstart** [comment]
@IntelligentDataMiner 

Please read previous posts in this issue:

https://github.com/bigdata-mindstorms/jekyll-playground/issues/11#issuecomment-195875166

**Comment by IntelligentDataMiner** [comment]
https://github.com/bigdata-mindstorms/jekyll-playground/blob/gh-pages/public/IntelligentDataMiner/2016/04/21/README.md
