### ISSUE TITLE
09: Jekyll + Bootstrap + d3 starter (shared version)

### ISSUE THREAD

**Issue by ontouchstart** [bigdata-mindstorms/jekyll-playground#12]
[This exercise](https://github.com/bigdata-mindstorms/jekyll-playground/tree/gh-pages/public/ontouchstart/2016/03/13
) is almost the same as [2016/03/12](https://github.com/bigdata-mindstorms/jekyll-playground/tree/gh-pages/public/ontouchstart/2016/03/12). The main difference is that we use a root level shared layout [_layouts/fancy.html](https://github.com/bigdata-mindstorms/jekyll-playground/blob/gh-pages/_layouts/fancy.html) which calls root level shared `bootstrap`, `jQuery` and `d3` libraries. 

https://github.com/bigdata-mindstorms/jekyll-playground/tree/gh-pages/public/ontouchstart/2016/03/13

**Comment by LivingProgram** [comment]
https://github.com/bigdata-mindstorms/jekyll-playground/tree/gh-pages/public/LivingProgram/2016/03/14/Lesson09

I will add/play around with some examples later, but @ontouchstart I cannot figure out how to add a file via git bash?

**Comment by ontouchstart** [comment]
Although [bash](https://github.com/denysdovhan/bash-handbook/blob/master/README.md) is out of the scope of this course, you are welcome to learn it by yourself and share your experience here: https://github.com/bigdata-mindstorms/node-playground/issues/2

**Comment by LivingProgram** [comment]
Sure thing, I will also post a simplified "cheat sheet" concerning the vim editor

**Comment by IntelligentDataMiner** [comment]
@ontouchstart 
Can you help me with my bootstrap examples.html file?
I am reading the console on my website and it says "SyntaxError: expected expression, got '.' "
I don't see any difference or errors in my code and I think the file sharing is correct.
Thanks a lot.
https://bigdata-mindstorms.github.io/jekyll-playground/public/IntelligentDataMiner/2016/04/24/bootstrap-examples.html**

**Comment by IntelligentDataMiner** [comment]
@ontouchstart 
nevermind, I think the website just didn't update
