### ISSUE TITLE
10: Jekyll + Bootstrap + d3 starter (container + data + function)

### ISSUE THREAD

**Issue by ontouchstart** [bigdata-mindstorms/jekyll-playground#13]
https://github.com/bigdata-mindstorms/jekyll-playground/tree/gh-pages/public/ontouchstart/2016/03/14

**Comment by LivingProgram** [comment]
https://github.com/bigdata-mindstorms/jekyll-playground/tree/gh-pages/public/LivingProgram/2016/03/15 
Still missing the bootstrap_examples_nav example, but I did comment on all other portions of the code

**Comment by ontouchstart** [comment]
Take a look at your comments, they are just the duplications of the code. 

That is OK for beginners who do not understand the idioms. Once you pass that level, you should not add comment noise to the code but more meaningful comments about __what__ and __why__ in the __commit message___. Leave __how__ to the code itself.

**Comment by ontouchstart** [comment]
__idioms__ is a powerful to compress contexts for human to communication. This partially answered your question:

https://github.com/bigdata-mindstorms/node-playground/issues/12#issuecomment-196587874

See how much context  information is compresses in the idiom
[举一反三](https://github.com/bigdata-mindstorms/d3-playground/issues/39).
