### ISSUE TITLE
01: 你好世界 作业区

### ISSUE THREAD

**Issue by ontouchstart** [bigdata-mindstorms/jekyll-playground#3]
[01: 你好世界](https://github.com/bigdata-mindstorms/jekyll-playground/tree/gh-pages/lessons/01)

**Comment by ontouchstart** [comment]
https://github.com/bigdata-mindstorms/jekyll-playground/blob/gh-pages/public/ontouchstart/README.md

**Comment by ontouchstart** [comment]
@chenxiaorong 

请按照要求做，不要画:snake: 添 :footprints: 

https://github.com/bigdata-mindstorms/jekyll-playground/tree/gh-pages/public/chenxiaorong

**Comment by shuairenchang** [comment]
https://github.com/bigdata-mindstorms/jekyll-playground/blob/gh-pages/public/shuairenchang/README.md

**Comment by wellido** [comment]
https://github.com/bigdata-mindstorms/jekyll-playground/blob/gh-pages/public/wellido/README.md

**Comment by TangKjjQiang** [comment]
https://github.com/bigdata-mindstorms/jekyll-playground/blob/gh-pages/public/TangKjjQiang/README.md

**Comment by VeroniqueSoleil** [comment]
https://github.com/bigdata-mindstorms/jekyll-playground/blob/gh-pages/public/VeroniqueSoleil/readme.md

**Comment by LivingProgram** [comment]
https://github.com/bigdata-mindstorms/jekyll-playground/blob/gh-pages/public/LivingProgram/README.md

**Comment by jabonzhang** [comment]
https://github.com/bigdata-mindstorms/jekyll-playground/blob/gh-pages/public/Jabonzhang/README.md

**Comment by s3931132** [comment]
https://github.com/bigdata-mindstorms/jekyll-playground/blob/gh-pages/public/s3931132/README.md

请教一下教授
>
http://bigdata-mindstorms.github.io/jekyll-playground/public/s3931132/
>

这个链接是怎样生成的呢？

**Comment by ontouchstart** [comment]
https://help.github.com/articles/user-organization-and-project-pages/

**Comment by s3931132** [comment]
谢谢教授，这个[链接](http://bigdata-mindstorms.github.io/jekyll-playground/public/s3931132/)是属于Project Pages site owned by an organization这个类型的吧？

**Comment by ontouchstart** [comment]
:+1:

**Comment by double126** [comment]
[https://bigdata-mindstorms.github.io/jekyll-playground/public/double126/README.md](https://bigdata-mindstorms.github.io/)

**Comment by ontouchstart** [comment]
@double126 :100:

**Comment by ontouchstart** [comment]
[02: markdown转换成html 作业区](https://github.com/bigdata-mindstorms/jekyll-playground/issues/4)

**Comment by haisenbergX** [comment]
[https://github.com/bigdata-mindstorms/jekyll-playground/blob/gh-pages/public/haisenbergX/REDAME.md](https://github.com/bigdata-mindstorms/jekyll-playground/blob/gh-pages/public/haisenbergX/REDAME.md)

**Comment by amarande** [comment]
https://github.com/bigdata-mindstorms/jekyll-playground/edit/gh-pages/public/amarande/README.md

**Comment by chenxiaorong** [comment]
https://github.com/bigdata-mindstorms/jekyll-playground/blob/gh-pages/public/chenxiaorong/README.md

**Comment by nnsghbb** [comment]
https://github.com/bigdata-mindstorms/jekyll-playground/blob/gh-pages/public/nnsghbb/README.md

**Comment by IntelligentDataMiner** [comment]
https://github.com/bigdata-mindstorms/jekyll-playground/blob/gh-pages/public/IntelligentDataMiner/2016/04/16/README.md
