### ISSUE TITLE
02: markdown转换成html 作业区

### ISSUE THREAD

**Issue by ontouchstart** [bigdata-mindstorms/jekyll-playground#4]
[02: markdown转换成html](https://github.com/bigdata-mindstorms/jekyll-playground/blob/gh-pages/lessons/02/README.md)

**Comment by ontouchstart** [comment]
http://bigdata-mindstorms.github.io/jekyll-playground/public/ontouchstart/

https://bigdata-mindstorms.github.io/jekyll-playground/public/ontouchstart/

http://bigdata-mindstorms.github.io/jekyll-playground/public/ontouchstart/markdown.md

http://bigdata-mindstorms.github.io/jekyll-playground/public/ontouchstart/html.html

**Comment by wellido** [comment]
http://bigdata-mindstorms.github.io/jekyll-playground/public/wellido/

http://bigdata-mindstorms.github.io/jekyll-playground/public/wellido/

http://bigdata-mindstorms.github.io/jekyll-playground/public/wellido/markdown.md

http://bigdata-mindstorms.github.io/jekyll-playground/public/wellido/html.html

**Comment by TangKjjQiang** [comment]
http://bigdata-mindstorms.github.io/jekyll-playground/public/TangKjjQiang/
http://bigdata-mindstorms.github.io/jekyll-playground/public/TangKjjQiang/
http://bigdata-mindstorms.github.io/jekyll-playground/public/TangKjjQiang/markdown.md
http://bigdata-mindstorms.github.io/jekyll-playground/public/TangKjjQiang/html.html

**Comment by haisenbergX** [comment]
[http://bigdata-mindstorms.github.io/jekyll-playground/public/haisenbergX/html.html](http://bigdata-mindstorms.github.io/jekyll-playground/public/haisenbergX/html.html)
[http://bigdata-mindstorms.github.io/jekyll-playground/public/haisenbergX/markdown.md](http://bigdata-mindstorms.github.io/jekyll-playground/public/haisenbergX/markdown.md)

**Comment by LivingProgram** [comment]
http://bigdata-mindstorms.github.io/jekyll-playground/public/LivingProgram/

https://bigdata-mindstorms.github.io/jekyll-playground/public/LivingProgram/

https://bigdata-mindstorms.github.io/jekyll-playground/public/LivingProgram/markdown.md

https://bigdata-mindstorms.github.io/jekyll-playground/public/LivingProgram/html.html

**Comment by shuairenchang** [comment]
http://bigdata-mindstorms.github.io/jekyll-playground/public/shuairenchang/

https://bigdata-mindstorms.github.io/jekyll-playground/public/shuairenchang/

https://bigdata-mindstorms.github.io/jekyll-playground/public/shuairenchang/markdown.md

https://bigdata-mindstorms.github.io/jekyll-playground/public/shuairenchang/html.html

**Comment by ontouchstart** [comment]
markdown 格式不对， "#" 后面要有空格。
”# "

**Comment by amarande** [comment]
https://github.com/bigdata-mindstorms/jekyll-playground/tree/gh-pages/public/amarande

https://github.com/bigdata-mindstorms/jekyll-playground/edit/gh-pages/public/amarande/README.md

https://github.com/bigdata-mindstorms/jekyll-playground/edit/gh-pages/public/amarande/index.html

https://github.com/bigdata-mindstorms/jekyll-playground/blob/gh-pages/public/amarande/html.md

https://github.com/bigdata-mindstorms/jekyll-playground/blob/gh-pages/public/amarande/markdown.md

**Comment by ontouchstart** [comment]
@amarande 

请仔细看看我的例子和其他人的网址的pattern.

**Comment by ontouchstart** [comment]
@amarande 还有我们这堂课的内容：https://github.com/bigdata-mindstorms/jekyll-playground/blob/gh-pages/lessons/02/README.md

**Comment by ontouchstart** [comment]
第三堂课开始了：
https://github.com/bigdata-mindstorms/jekyll-playground/tree/gh-pages/lessons/03/README.md

**Comment by chenxiaorong** [comment]
1.你好世界
> - http://bigdata-mindstorms.github.io/jekyll-playground/public/chenxiaorong/
>
> - https://bigdata-mindstorms.github.io/jekyll-playground/public/chenxiaorong/

2.markdown转换成html
> - https://bigdata-mindstorms.github.io/jekyll-playground/public/chenxiaorong/markdown.md
>
> - https://bigdata-mindstorms.github.io/jekyll-playground/public/chenxiaorong/html.md

**Comment by double126** [comment]
http://bigdata-mindstorms.github.io/jekyll-playground/public/double126/

https://bigdata-mindstorms.github.io/jekyll-playground/public/double126/

https://bigdata-mindstorms.github.io/jekyll-playground/public/double126/markdown.md

https://bigdata-mindstorms.github.io/jekyll-playground/public/double126/html.html

**Comment by nnsghbb** [comment]
http://bigdata-mindstorms.github.io/jekyll-playground/public/nnsghbb/
http://bigdata-mindstorms.github.io/jekyll-playground/public/nnsghbb/
http://bigdata-mindstorms.github.io/jekyll-playground/public/nnsghbb/markdown.md
http://bigdata-mindstorms.github.io/jekyll-playground/public/nnsghbb/html.html

**Comment by IntelligentDataMiner** [comment]
https://github.com/bigdata-mindstorms/jekyll-playground/blob/gh-pages/public/IntelligentDataMiner/2016/04/16/README.md
