### ISSUE TITLE
03: page_data 练习区

### ISSUE THREAD

**Issue by ontouchstart** [bigdata-mindstorms/jekyll-playground#5]
https://github.com/bigdata-mindstorms/jekyll-playground/tree/gh-pages/lessons/03

请把你们的测试网址或者更新后的README.md放在这里。

**Comment by ontouchstart** [comment]
Links for [lesson 03](https://github.com/bigdata-mindstorms/jekyll-playground/tree/gh-pages/lessons/03)

- https://bigdata-mindstorms.github.io/jekyll-playground/public/ontouchstart/page_data.html

- https://bigdata-mindstorms.github.io/jekyll-playground/public/ontouchstart/page_data.txt

- https://bigdata-mindstorms.github.io/jekyll-playground/public/ontouchstart/page_data.json

**Comment by ontouchstart** [comment]
https://github.com/bigdata-mindstorms/jekyll-playground/blob/gh-pages/public/ontouchstart/README.md

**Comment by wellido** [comment]
https://github.com/bigdata-mindstorms/jekyll-playground/blob/gh-pages/public/wellido/README.md

**Comment by haisenbergX** [comment]
[https://github.com/bigdata-mindstorms/jekyll-playground/blob/gh-pages/public/haisenbergX/REDAME.md](https://github.com/bigdata-mindstorms/jekyll-playground/blob/gh-pages/public/haisenbergX/REDAME.md)

**Comment by amarande** [comment]
https://github.com/bigdata-mindstorms/jekyll-playground/blob/gh-pages/public/amarande/README.md

**Comment by VeroniqueSoleil** [comment]
https://github.com/bigdata-mindstorms/jekyll-playground/blob/gh-pages/public/VeroniqueSoleil/readme.md

**Comment by chenxiaorong** [comment]
https://github.com/bigdata-mindstorms/jekyll-playground/blob/gh-pages/public/chenxiaorong/README.md

**Comment by LivingProgram** [comment]
https://github.com/bigdata-mindstorms/jekyll-playground/blob/gh-pages/public/LivingProgram/README.md

**Comment by TangKjjQiang** [comment]
https://github.com/bigdata-mindstorms/jekyll-playground/blob/gh-pages/public/TangKjjQiang/README.md

**Comment by ontouchstart** [comment]
@TangKjjQiang 你上面的作业结果最后一个链接有错误， 我帮你改过来了：https://github.com/bigdata-mindstorms/jekyll-playground/commit/3dbc24c975c927869669471ebfdd6272a029789d#commitcomment-16527858

以后请记住所有链接都要验证后再commit。不要浪费大家的时间替你检查。

**Comment by nnsghbb** [comment]
https://github.com/bigdata-mindstorms/jekyll-playground/blob/gh-pages/public/nnsghbb/README.md

**Comment by IntelligentDataMiner** [comment]
https://github.com/bigdata-mindstorms/jekyll-playground/blob/gh-pages/public/IntelligentDataMiner/2016/04/16/README.md
