### ISSUE TITLE
04: YAML 练习区

### ISSUE THREAD

**Issue by ontouchstart** [bigdata-mindstorms/jekyll-playground#6]
https://github.com/bigdata-mindstorms/jekyll-playground/tree/gh-pages/lessons/04

**Comment by LivingProgram** [comment]
我发现如果你在[yaml.md](https://github.com/bigdata-mindstorms/jekyll-playground/blob/gh-pages/lessons/04/yaml.md)里面不放：
```markdown
<script src="yaml.js"></script>
```
那么console里面就[不会一样](https://bigdata-mindstorms.github.io/jekyll-playground/public/LivingProgram/Lesson04/test_yaml.html)

**Comment by LivingProgram** [comment]
看来[yaml.md](https://bigdata-mindstorms.github.io/jekyll-playground/lessons/04/yaml.html) console里面有东西：
![image](https://cloud.githubusercontent.com/assets/16373135/13555123/129e3a1e-e386-11e5-808d-9720d49c80e3.png)
是因为[yaml.md文件](https://github.com/bigdata-mindstorms/jekyll-playground/edit/gh-pages/lessons/04/yaml.md)文件下面有：
```markdown
<script src="yaml.js"></script>
```
然后，你再看一看[yaml.js](https://github.com/bigdata-mindstorms/jekyll-playground/blob/gh-pages/lessons/04/yaml.js)文件下面有
```javascript
data = {{ page | jsonify }};
console.log(data);
```
是不是 `{{ page | jsonify}}`, 是把文件换成json, 这样用`console.log(data)`的时候，文件就在console里面出现了
# 总结一下
1. 我觉得[yaml.md](https://github.com/bigdata-mindstorms/jekyll-playground/blob/gh-pages/lessons/04/yaml.md) 是使用 [yaml.js](https://github.com/bigdata-mindstorms/jekyll-playground/blob/gh-pages/lessons/04/yaml.js) 来把data放进console里面
2. [yaml.js](https://github.com/bigdata-mindstorms/jekyll-playground/blob/gh-pages/lessons/04/yaml.js) 需要把data换成json ([yaml.json](https://github.com/bigdata-mindstorms/jekyll-playground/blob/gh-pages/lessons/04/yaml.json) 才能用上data

**Comment by amarande** [comment]
咨询老师几个问题：

1. 在yaml.js文件里，{{page | jsonify}} 把yaml格式转化成json格式，那yaml.json这文件有什么用？如果yaml.js里没有console.log(),那这两个文件一样，是否存成.js 或.json都可以？

2. 是不是yaml.md也会产生一个yaml.html文件。

**Comment by ontouchstart** [comment]
1. .js 和 .json 是人为的决定。前者是JavaScript 代码，后者是JSON文件。必须符合JSON语法，否则载入后会有错误。 格式请参照 http://json.org/。
通过Jekyll，我们实际上是用YAML格式来写数据，然后再转成机器容易处理的JSON。

2. 是的。这是Jekyll的一个约定。如果.md文件前面有YAML数据部分，哪怕是空数据，Jekyll会转成.html格式，文件名后缀也同样变化。（.js, .json, .css 等其它文件内容修改，但是不改文件后缀）。

**Comment by ontouchstart** [comment]
@amarande 

JSON 的例子：

https://github.com/mbostock/d3/wiki/Requests#d3_json
https://api.jquery.com/jquery.getjson/

**Comment by amarande** [comment]
谢谢！
