### ISSUE TITLE
Jekyll 制作的网页分享

### ISSUE THREAD

**Issue by ontouchstart** [bigdata-mindstorms/jekyll-playground#7]
欢迎大家分享自己发现的好的Jekyll制作的网页。

**Comment by ontouchstart** [comment]
https://arduinohistory.github.io
https://github.com/ArduinoHistory/arduinohistory.github.io

**Comment by amarande** [comment]
https://pages.github.com/
http://mmistakes.github.io/minimal-mistakes/

这是用google查的，如何知道这是用jekyll？

**Comment by ontouchstart** [comment]
https://github.com/mmistakes/minimal-mistakes/tree/gh-pages
