### ISSUE TITLE
05: 使用Jekyll layout

### ISSUE THREAD

**Issue by ontouchstart** [bigdata-mindstorms/jekyll-playground#8]
请大家自己看我的例子：

https://github.com/bigdata-mindstorms/jekyll-playground/tree/gh-pages/public/ontouchstart/2016/03/07

这两个文件内容几乎一样，差别是一个有[头信息](http://jekyll.bootcss.com/docs/frontmatter/)，一个没有。

- https://github.com/bigdata-mindstorms/jekyll-playground/blob/gh-pages/public/ontouchstart/2016/03/07/README.md
- https://github.com/bigdata-mindstorms/jekyll-playground/blob/gh-pages/public/ontouchstart/2016/03/07/index.md

练习完以后请把你的链接贴到这里。有问题这里问。

谢谢。

**Comment by ontouchstart** [comment]
Jekyll的[_layouts](https://github.com/bigdata-mindstorms/jekyll-playground/tree/gh-pages/_layouts)文件夹里的模版看起来和许多其他系统和构架模版（JSP／PHP等等）没有什么不同。但是作为一个静态文件生成器，比传统的服务器网页生成系统有一个很重要的区别，那就是__容器化__的概念。同样的内容，可以放在不同的容器里。这一节课就是让大家练习这样的概念：把内容和容器分开。

至于最后生成的网址是什么，大家不用太担心，Jekyll系统可以有[很多设置](http://jekyll.bootcss.com/docs/usage/)，网址设定是一个完全独立的话题，可以也应该分开讨论。我们这里是借用现成的[GitHub pages](https://help.github.com/categories/github-pages-basics/)的功能学习和练习这些重要概念，以后不一定会依赖这个平台。

这种把内容和容器分开的模块化思想对于大多数只习惯单一复杂系统（比如MS Word, PowerPoint, WordPress, Java，传统的IDE 等等 ）的人来说，需要一个概念变更的过程。大家多做练习才能体会其中多奥秘。:smile:

**Comment by wellido** [comment]
https://github.com/bigdata-mindstorms/jekyll-playground/tree/gh-pages/public/wellido/2016/03/08

**Comment by VeroniqueSoleil** [comment]
https://github.com/bigdata-mindstorms/jekyll-playground/tree/gh-pages/public/VeroniqueSoleil/2016/03/08

**Comment by LivingProgram** [comment]
https://github.com/bigdata-mindstorms/jekyll-playground/tree/gh-pages/public/LivingProgram/2016/03/08

**Comment by ontouchstart** [comment]
很不错，你们几个人可以互相看看其他同学的作业，从中间找到灵感。

这个练习主要是学习内容 + 容器 的概念，先不要急于考虑style。

**Comment by ontouchstart** [comment]
@TangKjjQiang 

https://github.com/bigdata-mindstorms/jekyll-playground/commit/93bf7912d26eebd3dc2c851c91b89b39253b78d4#commitcomment-16571471

**Comment by amarande** [comment]
https://github.com/bigdata-mindstorms/jekyll-playground/tree/gh-pages/public/amarande/03/07

**Comment by TangKjjQiang** [comment]
https://github.com/bigdata-mindstorms/jekyll-playground/tree/gh-pages/public/TangKjjQiang/2016/3/8

**Comment by ontouchstart** [comment]
@TangKjjQiang 

Still [one more error](https://github.com/bigdata-mindstorms/jekyll-playground/commit/fd192bc2cdb1a5d855e902d70901418785251b55#commitcomment-16608254) :smile:

**Comment by nnsghbb** [comment]
https://github.com/bigdata-mindstorms/jekyll-playground/tree/gh-pages/public/nnsghbb/2016/04/08

**Comment by ontouchstart** [comment]
@nnsghbb

Jekyll requires that your layout file has to be under the _layouts folder (don't ask me why :smile: )

https://github.com/bigdata-mindstorms/jekyll-playground/tree/gh-pages/_layouts/nnsghbb

**Comment by nnsghbb** [comment]
https://github.com/bigdata-mindstorms/jekyll-playground/tree/gh-pages/public/nnsghbb/2016/04/08

**Comment by nnsghbb** [comment]
想问一下这个自己做的这个网址是怎么生成的，我都是按别人的网址格式写的自己的

**Comment by ontouchstart** [comment]
你做事情不太仔细 （还是太不仔细？:smile:)

看看你的layout文件的路径

https://github.com/bigdata-mindstorms/jekyll-playground/tree/gh-pages/_layouts/nnsghbb/2016/4/8

对比一下这个文件里你引用的路径

https://github.com/bigdata-mindstorms/jekyll-playground/blob/gh-pages/public/nnsghbb/2016/04/08/index.md

**Comment by ontouchstart** [comment]
如果一切顺利，生成的网址在这里：

https://bigdata-mindstorms.github.io/jekyll-playground/public/nnsghbb/2016/04/08/index.html

仔细看看网址的模式。

**Comment by ontouchstart** [comment]
https://github.com/bigdata-mindstorms/jekyll-playground/commit/04b1d26031d92da5a28489f373b76b3d337250a2#commitcomment-17040205

**Comment by nnsghbb** [comment]
https://github.com/bigdata-mindstorms/jekyll-playground/tree/gh-pages/public/nnsghbb/2016/04/08

**Comment by IntelligentDataMiner** [comment]
Index.md
* https://github.com/bigdata-mindstorms/jekyll-playground/blob/gh-pages/public/IntelligentDataMiner/2016/04/17/index.md

Default.html
* https://github.com/bigdata-mindstorms/jekyll-playground/blob/gh-pages/_layouts/IntelligentDataMiner/2016/04/17/default.html

Website
* http://bigdata-mindstorms.github.io/jekyll-playground/public/IntelligentDataMiner/2016/04/17/index.html
