### ISSUE TITLE
06: 使用Jekyll include

### ISSUE THREAD

**Issue by ontouchstart** [bigdata-mindstorms/jekyll-playground#9]
规则见上次作业：https://github.com/bigdata-mindstorms/jekyll-playground/issues/8

新的例子在这里：
https://github.com/bigdata-mindstorms/jekyll-playground/tree/gh-pages/public/ontouchstart/2016/03/08

请大家按部就班，照:cat:画:cat: ，然后照:cat:画:tiger:， [举一反三](https://github.com/bigdata-mindstorms/d3-playground/issues/39)。

**Comment by ontouchstart** [comment]
include 是[容器化](https://github.com/bigdata-mindstorms/jekyll-playground/issues/8#issuecomment-193285041)以外的另一种模块化方式。 除了把内容用容器包装起来以外，内容本身也可以嵌套。被嵌套的内容（比如网页共享的导航条等等）可以放在不同的容器里。

容器包含的语法是：
```
{{ content }}
```

嵌套内容的语法是：
```
{% include ontouchstart/2016/03/08/test.md %}
{% include ontouchstart/2016/03/08/test.html %}
```
请注意文件夹路径名和文件名，后缀等细节。

请大家仔细看看下面的两个截图。一个是Jekyll生成的html网页的文件内容。一个是浏览器载入html后生成的[DOM结构](https://developer.mozilla.org/zh-CN/docs/Web/API/Document_Object_Model)。

然后根据我的源代码：https://github.com/bigdata-mindstorms/jekyll-playground/tree/gh-pages/public/ontouchstart/2016/03/08 搞清楚这个网页到底是怎么装配起来的。哪一部分从哪一块源代码过来的。


![screen shot 2016-03-08 at 3 14 26 pm](https://cloud.githubusercontent.com/assets/951921/13614977/176df428-e541-11e5-99b0-58dbfbb249c2.png)

![screen shot 2016-03-08 at 3 14 36 pm](https://cloud.githubusercontent.com/assets/951921/13614985/20a11d04-e541-11e5-87f0-a422405dc37d.png)

**Comment by VeroniqueSoleil** [comment]
https://github.com/bigdata-mindstorms/jekyll-playground/blob/gh-pages/public/VeroniqueSoleil/2016/03/09/README.md

**Comment by wellido** [comment]
https://github.com/bigdata-mindstorms/jekyll-playground/blob/gh-pages/public/wellido/2016/03/09/README.md

**Comment by LivingProgram** [comment]
I don't understand what is the difference between Jekyll and [DOM](https://developer.mozilla.org/zh-CN/docs/Web/API/Document_Object_Model), and are we using DOM or not?

**Comment by ontouchstart** [comment]
@LivingProgram 

Jekyll is just a text file transformer and assembler, no more, no less.

A text file is just a bunch of strings, whether it is in `.html`, or `.js`,  or `.css` format. 

When the file is __loaded__ into the browser,  a [DOM](https://developer.mozilla.org/zh-CN/docs/Web/API/Document_Object_Model) is __formed__ inside the browser. If everything goes well as planned the DOM will render a __visible__ webpage for the viewer. In the meantime, you can also use  Developer Tools/JavaScript Console to view and change the DOM.

To use a food metaphor, files are recipes, DOM is the meal.

**Comment by ontouchstart** [comment]
HTML

![screen shot 2016-03-09 at 8 52 02 pm](https://cloud.githubusercontent.com/assets/951921/13656919/12213c5c-e639-11e5-9e73-ca97e4b2fc25.png)


DOM

![screen shot 2016-03-09 at 8 53 07 pm](https://cloud.githubusercontent.com/assets/951921/13656924/19d9f9fc-e639-11e5-86d1-f5db26d01460.png)

**Comment by LivingProgram** [comment]
[README.md](https://github.com/bigdata-mindstorms/jekyll-playground/blob/gh-pages/public/LivingProgram/2016/03/09/README.md)

I also noticed that when you use `include` for a `.md` file, it also adds an id to the added element as shown below:
![image](https://cloud.githubusercontent.com/assets/16373135/13657162/188ed2b4-e63b-11e5-9304-3ec735a1ac95.png)
But the `.html` file did not add an id as shown below:
![image](https://cloud.githubusercontent.com/assets/16373135/13657193/447d67b4-e63b-11e5-95f4-848c496061ae.png)
Probably due to the way jekyll changes the `.md` files to a webpage, it always adds an id?

**Comment by LivingProgram** [comment]
Thanks! @ontouchstart

**Comment by ontouchstart** [comment]
@LivingProgram The details you marked in the screenshots are __exactly__ what I want you to discover by yourself !

:+1:

**Comment by ontouchstart** [comment]
@LivingProgram 

Can you do a test to see what would happen if your markdown has two headings with __exactly__ the same text? like this:

# head
# head

Hint: in DOM, each id should only appear once, otherwise it is not an id anymore. :smile: 
Show us the URL of the html generated by Jekyll.

**Comment by LivingProgram** [comment]
[URL](http://bigdata-mindstorms.github.io/jekyll-playground/public/LivingProgram/2016/03/10/jekyll_include_experiment/index.html) generated from Jekyll
Even though it is the same head, it still generates different ids as shown below:
![image](https://cloud.githubusercontent.com/assets/16373135/13668409/a61504ce-e68a-11e5-9588-187dfb0f9456.png)

**Comment by ontouchstart** [comment]
:100:

**Comment by amarande** [comment]
https://github.com/bigdata-mindstorms/jekyll-playground/blob/gh-pages/public/amarande/03/08/README.md

**Comment by TangKjjQiang** [comment]
https://github.com/bigdata-mindstorms/jekyll-playground/blob/gh-pages/public/TangKjjQiang/2016/3/11/README.md

**Comment by nnsghbb** [comment]
https://github.com/bigdata-mindstorms/jekyll-playground/blob/gh-pages/public/nnsghbb/2016/04/12/README.md

**Comment by IntelligentDataMiner** [comment]
https://github.com/bigdata-mindstorms/jekyll-playground/blob/gh-pages/public/IntelligentDataMiner/2016/04/18/README.md
